name: CD Pipeline

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install vsce
        run: npm install -g vsce

      - name: Find the latest successful CI
        uses: actions/github-script@v6
        id: get_ci_run
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml', // or numeric workflow ID
              status: 'success',
              branch: 'main',
              per_page: 1
            });
            if (runs.data.workflow_runs.length === 0) {
              throw new Error('No successful CI runs found');
            }
            return runs.data.workflow_runs[0].id;

      - name: Get name and version from package.json
        id: pkg
        run: |
          NAME=$(jq -r .name package.json)
          VERSION=$(jq -r .version package.json)
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download artifact
        run: |
          RUN_ID=${{ steps.get_ci_run.outputs.result }}
          ARTIFACTS_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts)

          ARTIFACT_URL=$(echo "$ARTIFACTS_JSON" | jq -r '.artifacts[] | select(.name=="${{ steps.pkg.outputs.name }}") | .archive_download_url')
          echo "Artifact URL: $ARTIFACT_URL"
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o artifact.zip "$ARTIFACT_URL"
          unzip artifact.zip

      - name: Publish to VS Code Marketplace
        run: |
          vsce publish --pat ${{ secrets.VSCE_TOKEN }} --packagePath ${{ steps.pkg.outputs.name }}-${{ steps.pkg.outputs.version }}.vsix

      - name: Create GitHub Release and upload .vsix
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
